feature_engineering:
  applicant_ethnicity_code_map:
    hispanic: [ 1 ]
    mexican: [ 11 ]
    puerto_rican: [ 12 ]
    cuban: [ 13 ]
    other_hispanic: [ 14 ]
    not_hispanic: [ 2 ]
    info_not_provided: [ 3 ]
    not_applicable: [ 4 ]
  co_applicant_ethnicity_code_map:
    hispanic: [ 1 ]
    mexican: [ 11 ]
    puerto_rican: [ 12 ]
    cuban: [ 13 ]
    other_hispanic: [ 14 ]
    not_hispanic: [ 2 ]
    info_not_provided: [ 3 ]
    not_applicable: [ 4 ]
    no_co_applicant: [ 5 ]
  applicant_race_code_map:
    american_indian_alaska_native: [ 1 ]
    asian: [ 2 ]
    asian_indian: [ 21 ]
    chinese: [ 22 ]
    filipino: [ 23 ]
    japanese: [ 24 ]
    korean: [ 25 ]
    vietnamese: [ 26 ]
    other_asian: [ 27 ]
    black_or_african_american: [ 3 ]
    pacific_islander: [ 4 ]
    native_hawaiian: [ 41 ]
    guamanian: [ 42 ]
    samoan: [ 43 ]
    other_pacific_islander: [ 44 ]
    white: [ 5 ]
    info_not_provided: [ 6 ]
    not_applicable: [ 7 ]
  co_applicant_race_code_map:
    american_indian_alaska_native: [ 1 ]
    asian: [ 2 ]
    asian_indian: [ 21 ]
    chinese: [ 22 ]
    filipino: [ 23 ]
    japanese: [ 24 ]
    korean: [ 25 ]
    vietnamese: [ 26 ]
    other_asian: [ 27 ]
    black_or_african_american: [ 3 ]
    pacific_islander: [ 4 ]
    native_hawaiian: [ 41 ]
    guamanian: [ 42 ]
    samoan: [ 43 ]
    other_pacific_islander: [ 44 ]
    white: [ 5 ]
    info_not_provided: [ 6 ]
    not_applicable: [ 7 ]
    no_co_applicant: [ 8 ]