feature_engineering:
  applicant_ethnicity_code_map:
    hispanic: [ 1, 11, 12, 13, 14 ]
    not_hispanic: [ 2 ]
    info_not_provided: [ 3 ]
    not_applicable: [ 4 ]
  co_applicant_ethnicity_code_map:
    other: [ 1, 11, 12, 13, 14, 3, 4 ]
    not_hispanic: [ 2 ]
    no_co_applicant: [ 5 ]
  applicant_race_code_map:
    other: [ 1, 2, 21, 22, 23, 24, 25, 26, 27, 4, 41, 42, 43, 44, 6, 7 ]
    black_or_african_american: [ 3 ]
    white: [ 5 ]
  co_applicant_race_code_map:
    other: [ 1, 2, 21, 22, 23, 24, 25, 26, 27, 3, 4, 41, 42, 43, 44, 6, 7 ]
    white: [ 5 ]
    no_co_applicant: [ 8 ]
  co_applicant_credit_scoring_model_map:
    beacon_5_0: [ 1 ]
    experian_fair_isaac: [ 2 ]
    fico_risk_04: [ 3 ]
    fico_risk_98: [ 4 ]
    vantage_2_0: [ 5 ]
    vantage_3_0: [ 6 ]
    other_or_multiple: [ 7, 8 ]
    none: [ 9, 10 ]
  exclude_from_ohe: [ "denied_flag", "combined_loan_to_value_ratio", "loan_term", "intro_rate_period", "prepayment_penalty_term", "income", "property_value", "loan_amount" ]
  applicant_credit_scoring_model_ohe_map:
    known_model: [1, 2, 4, 5, 6, 7]
    FICO_Risk_Score_Classic_04: [3]
    Other_credit_scoring_model: [8]
    Not_applicable: [9, 11, 12, 13, 14, 15]
  applicant_ethnicity_observed_ohe_map:
    collected: [1]
    not_collected: [2]
    not_applicable: [3]
  applicant_race_observed_ohe_map:
    collected: [ 1 ]
    not_collected: [ 2 ]
    not_applicable: [ 3 ]
  applicant_sex_ohe_map:
    collected: [ 1 ]
    not_collected: [ 2 ]
    not_applicable: [ 3, 4, 6 ]
  applicant_sex_observed_ohe_map:
    collected: [ 1 ]
    not_collected: [ 2 ]
    not_applicable: [ 3 ]
  business_or_commercial_purpose_ohe_map:
    primarily: [1]
    not_primarily: [0]
  co_applicant_age_ohe_map:
    age_35-44: ["35-44"]
    no_co_applicant: ["9999"]
    other: ["45-54", "55-64", "65-74", "8888", "<25", ">74"]
  co_applicant_age_above_62_ohe_map:
    yes: ["Yes"]
    no: ["No"]
  co_applicant_credit_scoring_model_ohe_map:
    known_model: [ 1, 2, 4, 5, 6, 7 ]
    FICO_Risk_Score_Classic_04: [ 3 ]
    Other_credit_scoring_model: [ 8 ]
    Not_applicable: [ 9, 11, 12, 13, 14, 15 ]
  co_applicant_ethnicity_observed_ohe_map:
    collected: [ 1 ]
    not_collected: [ 2 ]
    not_applicable: [ 3 ]
    no_co_applicant: [4]
  co_applicant_race_observed_ohe_map:
    collected: [ 1 ]
    not_collected: [ 2 ]
    not_applicable: [ 3 ]
    no_co_applicant: [ 4 ]
  co_applicant_sex_ohe_map:
    collected: [ 1 ]
    not_collected: [ 2 ]
    not_applicable: [ 3, 4, 6 ]
  co_applicant_sex_observed_ohe_map:
    collected: [ 1 ]
    not_collected: [ 2 ]
    not_applicable: [ 3 ]
    no_co_applicant: [ 4 ]
  construction_method_ohe_map:
    site: [1]
    manufactured: [2]
  debt_to_income_ratio_ohe_map:
    0_20: ["<20%"]
    20–30: ["20%-<30%"]
    30_36: ["30%-<36%"]
    37_40: ["37", "38", "39", "40"]
    41_44: ["41", "42", "43", "44"]
    45_47: ["45", "46", "47"]
    48_50: ["48", "49", "50"]
    50_60: ["50%-60%"]
    60_100: [">60%"]
    not_applicable: ["NA"]
  initially_payable_to_institution_ohe_map:
    yes: [1]
    no: [2]
    not_applicable: [3]
  interest_only_payment_ohe_map:
    yes: [1]
    no: [0, 2]
  lien_status_ohe_map:
    first: [1]
    subordinate: [2, 0]
  loan_purpose_ohe_map:
    home_purchase: [1]
    home_improve: [2]
    refi: [31, 32]
    other: [4]
    not_applicable: [5]
  loan_type_ohe_map:
    conventional: [1]
    va: [3]
    other: [2, 4]
  manufactured_home_land_property_interest_ohe_map:
    direct: [1]
    indirect: [2]
    paid_lease: [3]
    unpaid_lease: [4]
    not_applicable: [5]
  manufactured_home_secured_property_type_ohe_map:
    land: [1]
    not_land: [2]
    not_applicable: [3]
  negative_amortization_ohe_map:
    yes: [1]
    no: [0, 2]
  occupancy_type_ohe_map:
    primary: [1]
    secondary: [2]
    investment: [3]
  open_end_line_of_credit_ohe_map:
    yes: [1]
    no: [0, 2]
  other_non_amortizing_features_ohe_map:
    yes: [1]
    no: [0, 2]
  preapproval_ohe_map:
    yes: [1]
    no: [0, 2]
  reverse_mortgage_ohe_map:
    yes: [ 1 ]
    no: [ 0, 2 ]
  submission_of_application_ohe_map:
    direct: [1]
    indirect: [2]