hmda_raw: "data/interim/2024_combined_mlar_header.parquet"
hmda_2024_typed: "data/interim/hmda_2024_typed.parquet"
hmda_2024_model: "data/processed/hmda_2024_model.parquet"
hmda_2024_model_catboost: "data/processed/hmda_2024_model_catboost.parquet"
schema_summary: "docs/schema_summary.csv"
target_class_balance_graph: "docs/target_class_balance_graph.png"
train_index: "data/processed/train_index.csv"
test_index: "data/processed/test_index.csv"
train_index_catboost: "data/processed/train_index_catboost.csv"
test_index_catboost: "data/processed/test_index_catboost.csv"
log_reg_model: "models/logreg_model.pkl"
log_reg_roc: "reports/figures/logreg_roc.png"
log_reg_pr: "reports/figures/logreg_pr.png"
log_reg_metrics_csv: "reports/tables/logreg_metrics.csv"
random_forest_model: "models/random_forest_model.pkl"
random_forest_metrics_csv: "reports/tables/random_forest_metrics.csv"
random_forest_roc: "reports/figures/random_forest_roc.png"
random_forest_pr: "reports/figures/random_forest_pr.png"
hgbm_model: "models/hgbm_model.pkl"
hgbm_metrics_csv: "reports/tables/hgbm_metrics.csv"
hgbm_roc: "reports/figures/hgbm_roc.png"
hgbm_pr: "reports/figures/hgbm_pr.png"
mlp_model: "models/mlp_model.pkl"
mlp_metrics_csv: "reports/tables/mlp_metrics.csv"
mlp_roc: "reports/figures/mlp_roc.png"
mlp_pr: "reports/figures/mlp_pr.png"
catboost_model: "models/catboost_model.pkl"
catboost_metrics_csv: "reports/tables/catboost_metrics.csv"
catboost_roc: "reports/figures/catboost_roc.png"
catboost_pr: "reports/figures/catboost_pr.png"