hmda_raw: "data/interim/2024_combined_mlar_header.parquet"
hmda_2024_typed: "data/interim/hmda_2024_typed.parquet"
schema_summary: "docs/schema_summary.csv"
target_class_balance_graph: "docs/target_class_balance_graph.png"