hmda_raw: "data/interim/2024_combined_mlar_header.parquet"
hmda_2024_typed: "data/interim/hmda_2024_typed.parquet"
hmda_2024_model: "data/processed/hmda_2024_model.parquet"
schema_summary: "docs/schema_summary.csv"
target_class_balance_graph: "docs/target_class_balance_graph.png"
train_index: "data/processed/train_index.csv"
test_index: "data/processed/test_index.csv"
log_reg_model: "models/logreg_model.pkl"